name: Docker

on:
  release:
    types:
      - published

env:
  NIX_VERSION: nix-2.13.2
  NIXPKGS_CHANNEL: nixos-22.11
  CACHIX_NAME: golden-gate-ggx
  OCTOLYTICS_DIMENSION_REPOSITORY_ID: 590614152
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  docker-build:
    strategy:
      matrix:
        runtime: [sydney, brooklyn]
      fail-fast: false
    runs-on: buildjet-32vcpu-ubuntu-2204
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./Dockerfile.${{ matrix.runtime }}
          push: true
          tags: |
            ggxdocker/ggxnode-${{ matrix.runtime }}-img:latest
            ggxdocker/ggxnode-${{ matrix.runtime }}-img:${{ github.event.release.tag_name }}
