name: Docker

on:
  release:
    types:
      - published
  push:
    branches:
      - main

env:
  NIX_VERSION: nix-2.13.2
  NIXPKGS_CHANNEL: nixos-22.11
  CACHIX_NAME: golden-gate-ggx
  OCTOLYTICS_DIMENSION_REPOSITORY_ID: 590614152
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  build-sydney:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./Dockerfile.sydney
          push: true
          tags: |
            ggxdocker/ggxnode-sydney-img:latest
            ggxdocker/ggxnode-sydney-img:${{ github.event.release.tag_name }}
            ggxdocker/ggxnode-sydney-img:${{ steps.vars.outputs.sha_short }}

  build-brooklyn:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./Dockerfile.brooklyn
          push: true
          tags: |
            ggxdocker/ggxnode-brooklyn-img:latest
            ggxdocker/ggxnode-brooklyn-img:${{ steps.vars.outputs.sha_short }}

      - name: Add release tag
        if: github.event_name == 'release'
        run: echo "ggxdocker/ggxnode-brooklyn-img:${{ github.event.release.tag_name }}" >> release_tags.txt

      - name: Push release tag
        if: github.event_name == 'release'
        run: |
          IMAGE_ID=$(docker images -q ggxdocker/ggxnode-brooklyn-img:latest)
          if [ -n "$IMAGE_ID" ]; then
            docker tag ggxdocker/ggxnode-brooklyn-img:latest ggxdocker/ggxnode-brooklyn-img:${{ github.event.release.tag_name }}
            docker push ggxdocker/ggxnode-brooklyn-img:${{ github.event.release.tag_name }}
          else
            echo "Image ggxdocker/ggxnode-brooklyn-img:latest not found"
            exit 1
          fi
